export const UNIT_GROUPS = {
  basic: [
    'rawHp',
    'shield',
    'shieldEnable',
    'armorUpgrade',
    'armor',
    'buildTime',
    'minerals',
    'gas',
    'bwFlag',
    'buildScore',
    'destroyScore',
    'groundWeapon',
    'airWeapon',
    'maxGroundHits',
    'maxAirHits',
    'sightRange',
    'targetAcquisitionRange',
    'unitSize',
    'graphics',
    'supplyProvided',
    'supplyRequired',
    'spaceRequired',
    'spaceProvided',
  ],
  advanced: [
    'specialAbilityFlags',
    'movementFlags',
    'infestation',
    'subUnit1',
    'subUnit2'
  ],
  sound: [
    'readySound',
    'yesSoundStart',
    'yesSoundEnd',
    'whatSoundStart',
    'whatSoundEnd',
    'pissSoundStart',
    'pissSoundEnd'
  ],
  graphics: [],
  edit: [],
  ai: [],
  ui: [],
  req: []
}