export const UNIT_GROUPS = {
  basic: [
    'rawHp',
    'shield',
    'shieldEnable',
    'armorUpgrade',
    'armor',
    'buildTime',
    'minerals',
    'gas',
    'bwFlag',
    'buildScore',
    'destroyScore',
    'groundWeapon',
    'airWeapon',
    'maxGroundHits',
    'maxAirHits',
    'sightRange',
    'targetAcquisitionRange',
    'unitSize',
    'graphics',
    'supplyProvided',
    'supplyRequired',
    'spaceRequired',
    'spaceProvided',
  ],
  advanced: [],
  sound: [],
  graphics: [],
  edit: [],
  ai: [],
  ui: [],
  req: []
}